version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
    environment:
      DEBUG: true                       # available as: getenv('DEBUG');
      ENV_DEBUG: ${ENV_DEBUG}           # --- " ---, but value comes from .env file
      ENV_PROJECT: ${ENV_PROJECT}
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password    # this ENV var is mandatory
      MYSQL_DATABASE: testdb           # this creates a database (if it doesn't exist)
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData: